name: Hello
on: 
    push:
    workflow_dispatch:
      inputs:
        greeting:
          type: string
          default: Hello
          required: true
          description: A cheeful word

jobs:
 hello:
   runs-on: ubuntu-latest
   steps:
    - run: echo "${{ inputs.greeting }}"